- hosts: "{{ master_ip }}"
  tasks:
  - include: defaults/main.yml 
  - lvol:
      vg: "{{ vg_name }}"
      lv: "{{ lv_name }}"
      size: "{{ lv_size }}"
  - filesystem:
      fstype: "{{ fstype }}"
      dev: "{{ device }}"
      force: yes
  - file: 
      path: "{{ master_path }}"
      state: directory
      owner: apache
      mode: 0777
  - mount:
      path: "{{ master_path }}"
      src: "{{ device }}"
      fstype: "{{ fstype }}"
      state: mounted
  - lineinfile: 
      path: "/etc/exports"
      line: "{{ master_path }}  *(rw,no_root_squash)"
  - service: 
      name: "nfs" 
      state: restarted
      enabled: yes
- hosts: "{{ tenant_ip }}"
  tasks:
  - file:
      path: "{{ tenant_path }}"
      state: directory
      owner: apache
      mode: 0777
  - service:
      name: "firewalld"
      state: stopped
  - command: "mount {{ master_ip }}:{{ master_path }} {{ tenant_path }}"
  - mount: 
      path: "{{ tenant_ip }}"
      src: "{{ master_ip }}:{{ master_path }}"
      fstype: "{{ fstype }}"
      state: mounted
